### PR TITLE
Fix for typo in SempahoreExecutor

### LINKED ISSUE #24: Fix typo in "SempahoreExecutor"
https://github.com/thunkware/virtual-threads-bridge/blob/096fa0f06164fb2bacb3933636c09b70cc3d96bf/src/main/java/io/github/thunkware/vt/bridge/SempahoreExecutor.java#L18

My proposal is to deprecate the class "SempahoreExecutor.java" (due to the typo in its name) in favor of "SemaphoreExecutor.java"

I would perform these steps:

1. Create "SemaphoreExecutor.java" 
2. Move all the working code to the newly created class
3. Delegate all calls in "SempahoreExecutor.java" methods to the corresponding methods in "SemaphoreExecutor.java"
4. Mark "SempahoreExecutor.java" as deprecated for removal

The intention is not making a breaking change.

If you think it makes sense I can try to contribute a PR.

Thanks in advance

### PR DESCRIPTION
**Pull request by juliojgd**
Closes #24 

Changed static methods in ExecutorTools as well as tests and README doc

Tested `mvn clean install` working both with OpenJDK 17.0.11 and OpenJDK 21.0.3.

### CODE REVIEW

File: src/main/java/io/github/thunkware/vt/bridge/ExecutorTool.java [hunk 1]
```diff
@@ -99,12 +111,40 @@ public static ExecutorService newSempahoreVirtualExecutor(int permits) {
      * @param acquireTimeout time to wait for acquire a new task when no permit is
      *                       available
      * @return a new executor with limited concurrency
+     * @deprecated Because of typo in method name
      */
+    @Deprecated(forRemoval = true, since = "0.0.5")
```
Comment (maxxedev) [inline src/main/java/io/github/thunkware/vt/bridge/ExecutorTool.java:116]: can you please make this compatible with java8

**Comment by maxxedev** [comment]
thanks!
